services:
  - type: web
    name: academic-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn AITS_project.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: psua4*o1&+-r_5b=!#g*n9p)_oy0k+h4)sima0921u8ss%w(t2
